//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 08:40:50 PM CEST 
//


package situationtemplate.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tSituationTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSituationTemplate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="situationNode" type="{}tSituationNode" maxOccurs="unbounded"/>
 *         &lt;element name="operationNode" type="{}tOperationNode" maxOccurs="unbounded"/>
 *         &lt;element name="conditionNode" type="{}tConditionNode" maxOccurs="unbounded"/>
 *         &lt;element name="contextNode" type="{}tContextNode" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSituationTemplate", propOrder = {
    "situationNode",
    "operationNode",
    "conditionNode",
    "contextNode"
})
public class TSituationTemplate {

    @XmlElement(required = true)
    protected List<TSituationNode> situationNode;
    @XmlElement(required = true)
    protected List<TOperationNode> operationNode;
    @XmlElement(required = true)
    protected List<TConditionNode> conditionNode;
    @XmlElement(required = true)
    protected List<TContextNode> contextNode;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the situationNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the situationNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSituationNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSituationNode }
     * 
     * 
     */
    public List<TSituationNode> getSituationNode() {
        if (situationNode == null) {
            situationNode = new ArrayList<TSituationNode>();
        }
        return this.situationNode;
    }

    /**
     * Gets the value of the operationNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperationNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TOperationNode }
     * 
     * 
     */
    public List<TOperationNode> getOperationNode() {
        if (operationNode == null) {
            operationNode = new ArrayList<TOperationNode>();
        }
        return this.operationNode;
    }

    /**
     * Gets the value of the conditionNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conditionNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConditionNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TConditionNode }
     * 
     * 
     */
    public List<TConditionNode> getConditionNode() {
        if (conditionNode == null) {
            conditionNode = new ArrayList<TConditionNode>();
        }
        return this.conditionNode;
    }

    /**
     * Gets the value of the contextNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contextNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContextNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TContextNode }
     * 
     * 
     */
    public List<TContextNode> getContextNode() {
        if (contextNode == null) {
            contextNode = new ArrayList<TContextNode>();
        }
        return this.contextNode;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
